apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
  namespace: omeka
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
  MYSQL_DATABASE: "omeka_s"
  MYSQL_USER: "omeka"
  MYSQL_PASSWORD: "changeme-omeka-pw"
