apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-deployer
  namespace: omeka
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-deployer-token
  namespace: omeka
  annotations:
    kubernetes.io/service-account.name: gitlab-deployer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
  namespace: omeka
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-deployer-binding
  namespace: omeka
subjects:
  - kind: ServiceAccount
    name: gitlab-deployer
    namespace: omeka
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io
