apiVersion: "libnamic.omk/v1"
kind: "OmekaSProject"

project:
  name: "omeka-k8s"
  description: "Omeka S image for Kubernetes deployment"
  image:
    name: "registry.gitlab.com/manusolmel/cicd_omekas_manifest/omeka-k8s"

base:
  image: "giocomai/omeka-s-docker"
  tag: "v4.2.0"
  digest: "sha256:89169955b6090d8357d576072f34b239e533d50bf711094fb9b718a713b08741"

extensions:
  modules:
    - name: "Mapping"
      source:
        type: "catalog"
        version: "2.2.0"
        sha256: "36c27fc79207517364c6d4f88d28facc3c1b672fdb5ed5ddf046fa951c156a3b"
   
    - name: "Sharing"
      source:
        type: "catalog"
        version: "1.5.0"
        sha256: "e097b7b95fbc3bd7e6ffce595c2582f7aa2b2a3b16bcd20966b27f6b6fa44979"

    - name: "ValueSuggest"
      source:
        type: "release_zip"
        repo: "https://github.com/omeka-s-modules/ValueSuggest"
        version: "v1.20.0"
        asset: "ValueSuggest-1.20.0.zip"
        sha256: "a948f2fa36d630cc4f19987685557b03b57b36ffd9a19b3aba01846431f7a558"

  themes:
    - name: "Default"
      source:
        type: "catalog"
        version: "1.9.2"
        sha256: "f1cf865576bfb9b2d1a0a65e13a278d57c4626fcc4cd9ce96908ec33675a25f6"

    - name: "freedom"
      source:
        type: "git"
        repo: "https://github.com/omeka-s-themes/freedom.git"
        ref: "v1.1.0"

build:
  enable_tests: true
  target_tags:
    - "staging"
