apiVersion: "libnamic.omk/v1"
kind: "OmekaSProject"

project:
  name: "test-catalog-only"
  description: "Prueba con módulos y temas solo desde catálogo oficial"
  image:
    name: "registry.gitlab.com/manusolmel/cicd_omekas_manifest/omeka-test-catalog"

base:
  image: "giocomai/omeka-s-docker"
  tag: "latest"

extensions:
  modules:
    - name: "Mapping"
      source:
        type: "catalog"
        version: "2.2.0"
    - name: "CSVImport"
      source:
        type: "catalog"
        version: "2.6.1"
  themes:
    - name: "Default"
      source:
        type: "catalog"
        version: "1.9.2"

build:
  enable_tests: true
  target_tags:
    - "staging"